name: A Life Awake
favicon: null
layout_spectrum: 0.95655
typography_spectrum: 0.38481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeb4b2'
    - '#878d8b'
    - '#5097b3'
    - '#606a6c'
    - '#2a728b'
  brandStrength: 0.7783184670843184
  lightness: 0.01354200392961502
  saturation: 0.24200159730389714
  rhythmicContrast: 0.06784289865754545
purpose: []
